version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      WORDPRESS_USER1: ${WORDPRESS_USER1}
      WORDPRESS_USER1_PASSWORD: ${WORDPRESS_USER1_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      retries: 3

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_USER1: ${WORDPRESS_USER1}
      WORDPRESS_USER1_PASSWORD: ${WORDPRESS_USER1_PASSWORD}
      WORDPRESS_DB_HOST: mariadb:3306
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WORDPRESS_ADMIN_NAME: ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER1_EMAIL: ${WORDPRESS_USER1_EMAIL}
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    
networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb_volume1

  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress_volume1
