version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
      - volume_db:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      WORDPRESS_U: ${WORDPRESS_U}
      WORDPRESS_U_PASSWORD: ${WORDPRESS_U_PASSWORD}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      retries: 3

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    volumes:
      - volume_wp:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    environment:
      WORDPRESS_U: ${WORDPRESS_U}
      WORDPRESS_U_PASSWORD: ${WORDPRESS_U_PASSWORD}
      WORDPRESS_U_EMAIL: ${WORDPRESS_U_EMAIL}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_HOST: mariadb:3306
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WORDPRESS_A_NAME: ${WORDPRESS_A_NAME}
      WORDPRESS_A_PASSWORD: ${WORDPRESS_A_PASSWORD}
      WORDPRESS_A_EMAIL: ${WORDPRESS_A_EMAIL}
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    ports: 
      - "443:443"
    volumes:
      - volume_wp:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  volume_wp:
    driver_opts:
      o: bind
      type: none
      device: ~/home/obrittne/data/wordpress_volume1

  volume_db:
    driver_opts:
      o: bind
      type: none
      device: ~/home/obrittne/data/mariadb_volume1


