FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y && apt-get install -y php php7.4-fpm php-gd wget php-mysqli 

RUN mkdir -p /var/www/html /run/php

RUN chown -R www-data:www-data /var/www/html
RUN chown -R www-data:www-data /run/php


RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && \
	mv wp-cli.phar /usr/local/bin/wp

WORKDIR /var/www/html

COPY ./tools/wp_init.sh /setup_wp.sh
COPY ./tools/www.conf /etc/php/7.4/fpm/pool.d/www.conf

RUN  chmod +x /setup_wp.sh
# RUN apt-get install nano

CMD ["/setup_wp.sh"]
